###

GET http://localhost:8080/users

###

GET http://localhost:8080/users/1

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "Abc1234!"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Abc1234!"
}